version: '3.9'

services:
  webui:
    image: sammrai/sd-forge-docker:12.4.0-latest
    volumes:
      - "./data:/app/data"
    environment:
      ARGS: "--listen --enable-insecure-extension-access --port 7680 --api --api-server-stop"
      CIVITAI_TOKEN: $CIVITAI_TOKEN
    ports:
      - "7680:7680"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
