version: '3.9'

services:
  webui:
    image: sammrai/sd-forge-docker:12.4.0-latest
    volumes:
      - "./data:/app/data"
    environment:
      ARGS: "--listen --enable-insecure-extension-access --port 7680 --api"
      CIVITAI_TOKEN: $CIVITAI_TOKEN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
