version: '3.9'

services:
  webui:
    image: sammrai/sd-forge-docker:12.1.0
    volumes:
      - "./data:/app/data"
    environment:
      ARGS: "--listen --enable-insecure-extension-access --port 7680 --api --api-server-stop --always-cpu --skip-torch-cuda-test --skip-install"
      CIVITAI_TOKEN: ${CIVITAI_TOKEN:-''}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "7680:7680"
