services:
  webui:
    build: .
    volumes:
      - "./data:/app/data"
    environment:
      ARGS: "--listen --enable-insecure-extension-access --port 7680 --api"
      WEBUI_DIR: /app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
