name: Create and publish a Docker image

on:
  push:
    branches:
      - "main"
      - "test"
      - "gh-pages"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cuda_version: 12.1.0
            pytorch_version: 2.3.1
          - cuda_version: 12.4.0
            pytorch_version: 2.4
    env:
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Adjutment docker volumes
        run: |
          docker system df
          docker system prune -a --volumes -f
          docker system df
          df

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            CUDA_VERSION=${{ matrix.cuda_version }}
            PYTORCH_VERSION=${{ matrix.pytorch_version }}
          tags: |
            ${{ github.repository }}:${{ matrix.cuda_version }}-${{ env.SHORT_SHA }}
            ${{ github.repository }}:${{ matrix.cuda_version }}
          cache-from: type=registry,ref=${{ github.repository }}:cache-${{ matrix.cuda_version }}
          cache-to: type=registry,ref=${{ github.repository }}:cache-${{ matrix.cuda_version }},mode=max

